version: '3'
services:
  postgres-db:
    image: 'postgres:alpine'
    container_name: postgres-container
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

  api-meeting-room:
    container_name: meeting-room-container
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres-db
    networks:
      - app-network
    ports:
      - 8080:8080

volumes:
  postgres-volume:

networks:
  app-network:
    driver:
      bridge
