# =============================
# = Server
# =============================
server:
  port: 8080
  servlet:
    context-path: /v1
# =============================
# = Spring
# =============================
spring:
  profiles:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meeting-room-db
    username: postgres
    password: root
    type: com.zaxxer.hikari.HikariDataSource
