# =============================
# = Server
# =============================
server:
  port: 8080
  servlet:
    context-path: /api/v1
# =============================
# = Spring
# =============================
spring:
  profiles:
    active: sit
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



