# =============================
# = Spring
# =============================
spring:
  profiles:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meeting-room-db
    username: postgres
  flyway:
    locations: classpath:/db/migration/postgresql


